export default [
  {
    userName: "Sam Altman",
    userEmail: "samaltman@gmail.com",
    riskLevel: "Medium",
    triggerReason: "IP Change",
    actionReason: "Flagged",
    inQueueFor: "4 days",
    date: "12 Oct, 2023",
    previouslyReviewed: "Yes",
    reviewDate: "23 Aug,2023",
    actionTakenByName: "Neil",
    actionTakenByEmail: "neil@juno.com",
    status: "pending",
  },
  {
    userName: "Sameer Choubey",
    userEmail: "sameerchoubey@gmail.com",
    riskLevel: "High",
    triggerReason: "FIFO",
    actionReason: "Closed",
    inQueueFor: "4 days",
    date: "12 Oct, 2023",
    previouslyReviewed: "NO",
    reviewDate: "23 Aug,2023",
    actionTakenByName: "Pratik",
    actionTakenByEmail: "pratik@juno.com",
    status: "pending",
  },
  {
    userName: "Adarsh Panikkar",
    userEmail: "adarsh@gmail.com",
    riskLevel: "Low",
    triggerReason: "IP Change",
    actionReason: "Cleared",
    inQueueFor: "5 days",
    date: "12 Oct, 2023",
    previouslyReviewed: "NO",
    reviewDate: "23 Aug,2023",
    actionTakenByName: "Prashanth",
    actionTakenByEmail: "prashanth@juno.com",
    status: "pending",
  },
  {
    userName: "Pratik shetty",
    userEmail: "pratik3@gmail.com",
    riskLevel: "High",
    triggerReason: "FIFO",
    actionReason: "SOI requested",
    inQueueFor: "5 days",
    date: "12 Oct, 2023",
    previouslyReviewed: "Yes",
    reviewDate: "12 Sep,2024",
    actionTakenByName: "Rasleen Kaur",
    actionTakenByEmail: "rasleen@juno.com",
    status: "pending",
  },
  {
    userName: "Elon Musk",
    userEmail: "elon@twitterceo.com",
    riskLevel: "Low",
    triggerReason: "FIFO",
    actionReason: "Flagged",
    inQueueFor: "5 days",
    date: "12 Oct, 2023",
    previouslyReviewed: "Yes",
    reviewDate: "12 Sep,2024",
    actionTakenByName: "Pratik Shetty",
    actionTakenByEmail: "pratik@juno.com",
    status: "pending",
  },
  {
    userName: "Tirna Kundu",
    userEmail: "tirna@juno.com",
    riskLevel: "Low",
    triggerReason: "FIFO",
    actionReason: "Closed",
    inQueueFor: "5 days",
    date: "12 Oct, 2023",
    previouslyReviewed: "Yes",
    reviewDate: "12 Sep,2024",
    actionTakenByName: "Varun Deshpande",
    actionTakenByEmail: "varun@juno.com",
    status: "pending",
  },
  {
    userName: "Amanda Johnson",
    userEmail: "amanda.johnson@gmail.com",
    riskLevel: "Medium",
    triggerReason: "IP Change",
    actionReason: "Flagged",
    inQueueFor: "3 days",
    date: "15 Oct, 2023",
    previouslyReviewed: "Yes",
    reviewDate: "10 Oct, 2023",
    actionTakenByName: "Chris",
    actionTakenByEmail: "chris@example.com",
    status: "completed",
  },
  {
    userName: "Rahul Kapoor",
    userEmail: "rahul.kapoor@example.com",
    riskLevel: "High",
    triggerReason: "FIFO",
    actionReason: "Closed",
    inQueueFor: "2 days",
    date: "18 Oct, 2023",
    previouslyReviewed: "No",
    reviewDate: "26 Oct, 2023",
    actionTakenByName: "Ronik",
    actionTakenByEmail: "ronik@juno.com",
    status: "completed",
  },
  {
    userName: "Eva Rodriguez",
    userEmail: "eva.rodriguez@email.com",
    riskLevel: "Low",
    triggerReason: "IP Change",
    actionReason: "SOI requested",
    inQueueFor: "1 day",
    date: "20 Oct, 2023",
    previouslyReviewed: "Yes",
    reviewDate: "19 Oct, 2023",
    actionTakenByName: "Daniel",
    actionTakenByEmail: "daniel@email.com",
    status: "completed",
  },
  {
    userName: "Nina Patel",
    userEmail: "nina.patel@gmail.com",
    riskLevel: "High",
    triggerReason: "FIFO",
    actionReason: "Flagged",
    inQueueFor: "3 days",
    date: "22 Oct, 2023",
    previouslyReviewed: "No",
    reviewDate: "13 Oct, 2023",
    actionTakenByName: "Nilone",
    actionTakenByEmail: "nilone@juno.com",
    status: "completed",
  },
  {
    userName: "Greg Turner",
    userEmail: "greg.turner@example.net",
    riskLevel: "Medium",
    triggerReason: "IP Change",
    actionReason: "Closed",
    inQueueFor: "5 days",
    date: "25 Oct, 2023",
    previouslyReviewed: "Yes",
    reviewDate: "24 Oct, 2023",
    actionTakenByName: "Sophie",
    actionTakenByEmail: "sophie@example.com",
    status: "completed",
  },
  {
    userName: "Isaac Newton",
    userEmail: "isaac.newton@email.net",
    riskLevel: "Low",
    triggerReason: "FIFO",
    actionReason: "SOI requested",
    inQueueFor: "1 day",
    date: "28 Oct, 2023",
    previouslyReviewed: "Yes",
    reviewDate: "27 Oct, 2023",
    actionTakenByName: "Olivia",
    actionTakenByEmail: "olivia@email.net",
    status: "completed",
  },
];
