const employeeData = [
  {
    userName: "Sam Altman",
    userEmail: "samaltman@gmail.com",
    riskLevel: "Medium",
    triggerReason: "IP Change",
    actionReason: "Flagged",
    inQueueDay: "4 days",
    date: "12 Otc,2023",
    priviouslyReviewed: "Yes",
    reviewDate: "23 Aug,2023",
    actionTakenByName: "Neil",
    actionTakenByEmail: "neil@juno.com",
    status: "pending",
  },
  {
    userName: "Sameer Choubey",
    userEmail: "sameerchoubey@gmail.com",
    riskLevel: "High",
    triggerReason: "FIFO",
    actionReason: "Closed",
    inQueueDay: "4 days",
    date: "12 Otc,2023",
    priviouslyReviewed: "NO",
    reviewDate: "23 Aug,2023",
    actionTakenByName: "Pratik",
    actionTakenByEmail: "pratik@juno.com",
  },
  {
    userName: "Adarsh Panikkar",
    userEmail: "adarsh@gmail.com",
    riskLevel: "Low",
    triggerReason: "IP Change",
    actionReason: "Cleared",
    inQueueDay: "5 days",
    date: "12 Otc,2023",
    priviouslyReviewed: "NO",
    reviewDate: "23 Aug,2023",
    actionTakenByName: "Prashanth",
    actionTakenByEmail: "prashanth@juno.com",
  },
  {
    userName: "Pratik shetty",
    userEmail: "pratik3@gmail.com",
    riskLevel: "High",
    triggerReason: "FIFO",
    actionReason: "SOI requested",
    inQueueDay: "5 days",
    date: "12 Otc,2023",
    priviouslyReviewed: "Yes",
    reviewDate: "12 Sep,2024",
    actionTakenByName: "Rasleen Kaur",
    actionTakenByEmail: "rasleen@juno.com",
  },
  {
    userName: "Elon Musk",
    userEmail: "elon@twitterceo.com",
    riskLevel: "Low",
    triggerReason: "FIFO",
    actionReason: "Flagged",
    inQueueDay: "5 days",
    date: "12 Otc,2023",
    priviouslyReviewed: "Yes",
    reviewDate: "12 Sep,2024",
    actionTakenByName: "Pratik Shetty",
    actionTakenByEmail: "pratik@juno.com",
  },
  {
    userName: "Tirna Kundu",
    userEmail: "tirna@juno.com",
    riskLevel: "Low",
    triggerReason: "FIFO",
    actionReason: "Closed",
    inQueueDay: "5 days",
    date: "12 Otc,2023",
    priviouslyReviewed: "Yes",
    reviewDate: "12 Sep,2024",
    actionTakenByName: "Varun Deshpande",
    actionTakenByEmail: "varun@juno.com",
  },
];

export default employeeData;
